---
name: Upgrade Dependencies
on: [workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.STUDIO_GITHUB_TOKEN }}
      - uses: actions/setup-node@v4
        with:
          node-version: '24'
      - run: git config --global user.email "blah+pakkun@cliffano.com"
      - run: git config --global user.name "pakkunbot"
      - run: npm install -g bob@4
      - run: bob updep build
      - run: git commit -am "Upgrade dependencies to latest"
      - uses: ad-m/github-push-action@v0.8.0
        with:
          tags: true
          github_token: ${{ secrets.STUDIO_GITHUB_TOKEN }}
          branch: ${{ github.ref }}
